name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Get dependencies
      run: |
        go mod tidy
        go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Get dependencies
      run: |
        go mod tidy
        go mod download

    - name: Build all platforms
      run: make build-all

    - name: Verify binaries
      run: |
        file dist/ecsy-darwin-amd64
        file dist/ecsy-darwin-arm64
        file dist/ecsy-linux-amd64
        file dist/ecsy-linux-arm64
        file dist/ecsy-windows-amd64.exe